### ISSUE TITLE
Display pomodoros done

### ISSUE THREAD

**Issue by Yoi-Nami-Ra** [coddingtonbear/taskwarrior-pomodoro#11]
I would like to have me displayed amount of full pomodoros done today.

Either by number or graphically:

> ![tw pom_track_poms_daily](https://cloud.githubusercontent.com/assets/659598/12971650/bf3fe066-d09d-11e5-9b2c-17231143a08d.png)

**Comment by coddingtonbear** [comment]
Released as part of 1.4.0!  Thanks @Yoi-Nami-Ra!
