### ISSUE TITLE
Tag listed tasks with their respective projects

### ISSUE THREAD

**Issue by Yoi-Nami-Ra** [coddingtonbear/taskwarrior-pomodoro#12]
I would like to have them tasks to be additionally described with a project, so it would be easier for me to choose one.

Example mocup:
![tw pom_tag_with_project](https://cloud.githubusercontent.com/assets/659598/12971741/c22c4796-d09e-11e5-821a-317ce92aee78.png)

**Comment by coddingtonbear** [comment]
I can't tell if you're posting this hoping that I add such a feature, or if this is an indication that you're currently working on that; care to clarify?

**Comment by Yoi-Nami-Ra** [comment]
I thought that instead of dropping pull requests, I should create those, so it could have a chance of discussion.

All the ideas I did (or will ;) ) post here, I'm read to implement them myself.

Above is a mockup I did using playground.
Sorry for using your task list, but my head was empty for any other examples.

If you like it I'll start working on it right away.

**Comment by coddingtonbear** [comment]
Oh, totally; I like all of the ideas you've presented!  I think the only thing I'd recommend is maybe making them configurable -- some of my tasks have like a dozen tags on them, and I bet that'd make this specific display look a little hard-to-read.

**Comment by coddingtonbear** [comment]
(Also -- thank you so much for posting this before a PR!)

**Comment by beatgammit** [comment]
Is this still relevant given #30 (merged in #55) and #13 (I have a PR open: #60).

**Comment by beatgammit** [comment]
Closing since there's now a release with this feature in it. Please re-open if the released behavior isn't sufficient.
