### ISSUE TITLE
Sort tasks by urgency and group by project

### ISSUE THREAD

**Issue by Yoi-Nami-Ra** [coddingtonbear/taskwarrior-pomodoro#13]
I would like to have them sorted by urgency (most urgent on the top) and grouped by project.

Sorting and grouping should be optional.
It should be possible to use other variables.

If both sorting and grouping enabled, first element of the group decides on its position in the list.

Example mocup:
![tw pom_group_by_project](https://cloud.githubusercontent.com/assets/659598/12971847/c4f7960a-d09f-11e5-8e77-c8d68a0c3ff2.png)

**Comment by guenti** [comment]
+1

**Comment by amitkot** [comment]
+1

**Comment by novalis111** [comment]
I would love to see this feature implemented. My task descriptions are like "Run script to clean up database", and w/o project/tags displayed it's hard to pick the right one. Thanks for creating this tool anyway, love pomodoro!

**Comment by dodds-1** [comment]
any chance of having this added?

**Comment by coddingtonbear** [comment]
Totally willing to review a pull request!
