### ISSUE TITLE
Multiple releases?

### ISSUE THREAD

**Issue by adamgibbins** [coddingtonbear/taskwarrior-pomodoro#16]
It appears the project has two independent release mechanisms.

The readme.md links http://coddingtonbear-public.s3.amazonaws.com/github/taskwarrior-pomodoro/releases/taskwarrior-pomodoro-1.4.0.dmg as the current latest version.

Yet the GitHub Releases feature is also turned on: https://github.com/coddingtonbear/taskwarrior-pomodoro/releases - this shows 1.3.0 as the latest.

The version number would suggest the one mentioned in the readme.md, outside of the Releases feature is the latest. In which case can I suggest turning the GitHub Releases feature off to avoid confusion?

Thanks

**Comment by coddingtonbear** [comment]
The "Releases" tab shown on a Github repository is really just a zip archive corresponding to every tag that is pushed up.  As far as I'm aware, there is no way to disable said feature, and it wouldn't include the compiled app anyway, so I'm not sure it's terribly relevant for your interests anyway.

In this specific case, it looks like I neglected to push up tags last time I built a release; I'll push the tag in just a minute to resolve the discrepancy.
