### ISSUE TITLE
Ability to use Taskwarrior contexts

### ISSUE THREAD

**Issue by adamgibbins** [coddingtonbear/taskwarrior-pomodoro#17]
Taskwarrior-Pomodoro supports filters via the `pomodoro.defaultFilter` option, this is great. However taskwarrior already has a [context system](http://taskwarrior.org/docs/context.html) built in, which I set automatically based on my location (using an external system out of the scope of this issue) - it'd be great if Taskwarrior-pomodoro abided by the currently set context so I didn't need to duplicate my filter.

Thanks!

**Comment by coddingtonbear** [comment]
@adamgibbins; I don't personally use contexts at the moment, so it's very unlikely that I'll end up working on this, but if you were to implement such a feature, I can't think of a reason I wouldn't merge it.

Cheers, and let me know if you need any pointers about where to get started!
