### ISSUE TITLE
Beachball on startup

### ISSUE THREAD

**Issue by kmarekspartz** [coddingtonbear/taskwarrior-pomodoro#2]
Not sure why, but I'm getting a beachball on startup. Next steps will be to build it myself and debug in Xcode.

Mac OS X 10.10

```
$ task --version
2.5.0
```

**Comment by kmarekspartz** [comment]
I've used Menubar Countdown before and have been using taskwarrior for a few months... This seems like a perfect combination of the two. Looking forward to getting it working!

**Comment by kmarekspartz** [comment]
Getting rid of `task.waitUntilExit()` seems to have made the halt go away. I'm going to learn more about NSTask before I file a PR.

**Comment by coddingtonbear** [comment]
Hmm; if you don't `waitUntilExit`, the process is _probably_ still running; I wonder what might be causing it to halt waiting for input.

**Comment by kmarekspartz** [comment]
The JSON output fix for 1.0.2 must have fixed this, too.
