### ISSUE TITLE
Illegal instruction when ~/.taskrc is missing

### ISSUE THREAD

**Issue by mike-kfed** [coddingtonbear/taskwarrior-pomodoro#20]
When ~/.taskrc is not there:

mac:~ user$ /Applications/Taskwarrior\ Pomodoro.app/Contents/MacOS/Taskwarrior\ Pomodoro
Illegal instruction: 4 

A nasty crash, checking if this file exists before trying to read it would be more stable. (Swift actually scares me here, because illegal instruction normally makes me think the binary was compiled for another cpu architecture not something harmless like "file does not exist")

**Comment by coddingtonbear** [comment]
Yeah, agreed -- that would be better.  Could you file a pull request checking for that?
