### ISSUE TITLE
Enable automatic launching at login

### ISSUE THREAD

**Issue by coddingtonbear** [coddingtonbear/taskwarrior-pomodoro#24]
https://blog.timschroeder.net/2012/07/03/the-launch-at-login-sandbox-project/

**Comment by Crisses** [comment]
You can already do this: system preferences->Users & Groups -> your user tab "Login Items" hit the + at the bottom, find Taskwarrior Pomodoro.app and add it to the list.  This will launch the app with your other login items as seen in my screenshot (Alfred, Dropbox, etc.).

![screen shot 2017-10-15 at 4 13 19 pm](https://user-images.githubusercontent.com/14567348/31588711-ec67949a-b1c3-11e7-8db0-a138dca7aed8.png)

**Comment by coddingtonbear** [comment]
Ahh!  Nice -- I had no idea that was a thing you could do so easily.  Thanks for the tip, @Crisses .
