### ISSUE TITLE
Add Project Name to task list

### ISSUE THREAD

**Issue by mattmartini** [coddingtonbear/taskwarrior-pomodoro#30]
The project names (preferably outdented) should appear in the task list.

**Comment by coddingtonbear** [comment]
Hey there @mattmartini -- I don't have a whole lot of time to throw around at projects these days, but that sounds nice to me.  Could you post a pull request adding that?

**Comment by beatgammit** [comment]
This looks to be implemented, and I have made some improvements in #60.

@coddingtonbear @mattmartini @Yoi-Nami-Ra  This can be closed.

**Comment by beatgammit** [comment]
This works on the current build, and I'll be making a new build soon with enhancements.
