### ISSUE TITLE
feature request: get current task and timer state from terminal

### ISSUE THREAD

**Issue by dmidlo** [coddingtonbear/taskwarrior-pomodoro#31]
There is the Post-Pomodoro Hook, but it would be amazing if there were a way to get (and maybe even set) the current task and timer state from the terminal. Similar to taskwarrior helper commands. (https://taskwarrior.org/docs/commands/_get.html)

e.g.  (something to this effect)
```
$ twpomo task  #outputs description of active task
$ twpomo time  #outputs current state of timer
$ twpomo pause
$ twpomo set <taskwarrior task id> #sets active task to X task
$ twpomo notify 300  # notifies to terminal the state of timer every X seconds
etc......
```

**Comment by coddingtonbear** [comment]
What I've been _thinking_ about doing is adding support for applescript; I haven't really had the time available to upgrade this to the modern swift, though, let alone make that change.  I think that'll solve this problem for you!  Have a look at #25.

Also -- if you happen to know a little more about swift than I do, maybe I could convince you into helping me out with the upgrade process?

Cheers!
