### ISSUE TITLE
1.7.0.1 crashing on Sierra with wheel of death

### ISSUE THREAD

**Issue by ssbarnea** [coddingtonbear/taskwarrior-pomodoro#32]
After start the app is just hanging. I took a sample and attached it.
[Sample of Taskwarrior Pomodoro.txt](https://github.com/coddingtonbear/taskwarrior-pomodoro/files/972803/Sample.of.Taskwarrior.Pomodoro.txt)

**Comment by coddingtonbear** [comment]
I'm not seeing this problem, @ssbarnea, on Sierra.  Are you sure you have taskwarrior installed?

If you do -- try running from the console by finding the `MacOS/Taskwarrior Pomodoro` binary inside the package and running it directly.  You might see messages on your console that reveal something important.

**Comment by coddingtonbear** [comment]
Closing for now given no response.  But if you do reply, I'd be glad to help you troubleshoot.
