### ISSUE TITLE
Play a sound when a pomodoro is over.

### ISSUE THREAD

**Issue by Gnossos** [coddingtonbear/taskwarrior-pomodoro#35]
Maybe this is already in T-P, but I don't see it. I'd like to see T-P play a sound whenever a time period ends.

**Comment by coddingtonbear** [comment]
Definitely a solid idea, and it probably wouldn't be too difficult to add.  Could you file a pull request adding that?

**Comment by jottr** [comment]
I would love to see this too. Constantly missing the end of a pomodoro. 

Additionaly, some form of (optionally persistant) notification would be really helpful. 
Displaying the remaining time in the menubar would also help a lot.
