### ISSUE TITLE
Set several time limits

### ISSUE THREAD

**Issue by Gnossos** [coddingtonbear/taskwarrior-pomodoro#36]
I'd like timewarrior-pomodoro to have at least four configurable time limits:

1. When the current pomodoro is over. (Suggest 25 min.)

2. After a brief rest. (Suggest 5 min.)

3. After a configurable number of pomodoros (Suggest 6  completed pomodoros)

4. A major break (after the number of pomodoros in #3 and lasting at least 15 min.

**Comment by coddingtonbear** [comment]
I'm afraid your second, third, and fourth suggestion would probably be better handled out-of-app, but it does seem like that kind of behavior could be scripted with the AppleScript interface (see #25; assuming I ever get to doing that).  Regarding the first suggestion, you can already configure the pomodoro duration; have a look at this part of the docs: https://github.com/coddingtonbear/taskwarrior-pomodoro#pomodoro-duration.

Cheers, and thanks for taking the time to make a suggestion!
