### ISSUE TITLE
Missing menu items: refresh and start/stop time

### ISSUE THREAD

**Issue by echosa** [coddingtonbear/taskwarrior-pomodoro#37]
Looking at the screenshot in the readme, it looks like Taskwarrior Pomodoro is supposed to have options to refresh and to start/stop the timer. I do not see either of these options. I just installed Taskwarrior for the first time, as well as Taskwarrior Pomodoro. I added a task from the command line with `task`, then opened Taskwarrior Pomodoro. I see the task I added, and I see an option to quit. That's all though. I don't see anything in the readme about needing to enable these options or menu items. Am I missing something obvious?

<img width="258" alt="screen shot 2017-09-04 at 11 39 52 am" src="https://user-images.githubusercontent.com/133786/30034273-e605e13e-9165-11e7-95a6-de92cf95d6cb.png">

**Comment by coddingtonbear** [comment]
Oh, it's just that the screenshot is out-of-date.  If you post a pull request fixing that screenshot with a reasonable list of tasks, I'd totally merge it.

To be clear -- twpomodoro will check for updated tasks when you click the menu item, and you won't see the 'stop' option until you have started tracking time against a task.

**Comment by echosa** [comment]
Oh, so starting the timer isn't a function of this program? I thought it was. I guess I misunderstood. Thanks for the clarification. 

> until you have started tracking time against a task

What do you mean by that? I'm new to taskwarrior. I don't see anything in the man page about starting timers, which is why I thought this program did that. I can start a task but not a timer.

**Comment by coddingtonbear** [comment]
Oh, no, starting a timer is a core function, but there isn't a *start* button -- you just select the task you want to start work on.  Once you've selected your task, the pomodoro begins, and you'll be notified when it ends.

**Comment by echosa** [comment]
Oh, I see now! Looks like it is working as intended, I just didn't understand the UI and how it related to the `task` command itself. I see now that `task start` (marking a task as in progress) is separate from the pomodoro timer provided by this app. I get it now. Thanks! Looking forward to using it!
