### ISSUE TITLE
Add version information (and maybe an auto-updater)

### ISSUE THREAD

**Issue by echosa** [coddingtonbear/taskwarrior-pomodoro#38]
Just some thoughts/suggestions.

I just downloaded Taskwarrior Pomodoro and am having problems, so I submitted a GitHub issue. Out of habit, I went to check the version of the app I had, but I see no way of getting that info (outside of actually going to the .app in Finder and using `Get Info`). Perhaps a non-clickable `Version: X.X` in the dropdown would be good to have? Or, perhaps an `About Taskwarrior Pomodoro` menu item that opens a typical "about" dialog?

Additionally, speaking of versions, any plans for auto-updating or updating from within the app? Or at least an ability to check for updates, even if we have to manually install them?

**Comment by coddingtonbear** [comment]
I don't have really any time for this project to do more than simple bug fixes, so I'm afraid adding those features will have to be on you -- please post a pull request adding an autoupdater or menu item indicating the current version (preferably as two separate PRs).  Feel free to chat with me in the #taskwarrior channel on Freenode if you want to discuss options, though.

Cheers!

**Comment by echosa** [comment]
If I figure out Xcode and Mac App programming a bit better and, more importantly, find some time, I'll consider doing this and submitting a PR. Thanks!
