### ISSUE TITLE
Hard coded "list" command?

### ISSUE THREAD

**Issue by Crisses** [coddingtonbear/taskwarrior-pomodoro#39]
I think right now Taskwarrior Pomodoro is hard-coded to use the "list" report.

I'd love to be able to change it to "unblocked" so I don't see tasks with dependencies cluttering my list.  Maybe there's another way to do it?

Otherwise, "list" could be the default, and there could be a setting allowing it to be changed in .taskrc.  If it's already allowed, it's not documented.

Thank you for this, much appreciated. Hope I can help others (unfortunately not an XCode person...).

**Comment by coddingtonbear** [comment]
I wonder if this is what you're looking for: https://github.com/coddingtonbear/taskwarrior-pomodoro#task-list-filter ?

**Comment by Crisses** [comment]
I don't know how to filter out so that only "unblocked" tasks are listed except:

> task unblocked

It's like "task list" except it only shows tasks that are not dependent on other tasks.  So for example I have a project to create a podcast.  I have to edit the podcast "task add edit podcast" = task 1.  "task add assemble podcast with intro/outro depends:1" will add task 2 that depends on task 1.

I want to only see task 1 because it's actionable.  I can't Pomodoro on task 2 until task 1 is complete.

**Comment by Crisses** [comment]
It's in the list of "reports" - one of which would be "task list" and there are others like "task unblocked" and "task next" which gives only the next 7 most urgent & actionable tasks.  Either of which would be nifty to use with the Taskwarrior Pomodoro.

https://taskwarrior.org/docs/report.html

**Comment by coddingtonbear** [comment]
This might not be clear from the source, but tools that interact with Taskwarrior programmatically don't use reports directly -- they instead use the `export` subcommand so they can obtain a list of tasks formatted in a machine-readable way.  That doesn't mean that what you're asking for is impossible, though, it just means that the path you thought you had to take isn't actually the way you get to where you want to be.

What you probably want to do, here, is identify what filters that specific report uses by default, and enter those in as your "list filter" -- if you don't know how to find that information, the folks in #taskwarrior on Freenode can surely point you in the right direction.  Hint: you might want to search Taskwarrior's docs for the term "virtual tag".

Cheers, and good luck!
