### ISSUE TITLE
Timer rolls over if Pomodoro finishes while computer is asleep

### ISSUE THREAD

**Issue by qbatten** [coddingtonbear/taskwarrior-pomodoro#43]
Downloaded this only half an hour ago, so haven't reproduced this bug under other circumstances yet. But, I had a pomodoro running, and closed my laptop when it was a few minutes away from done. When I came back, the text of the timer had rolled down past zero up to the max of whatever variable you're storing that value in (I think it was around 4 billion, so I guess it's an unsigned long or something?). After about 30 seconds, I got a notification that the Pomodoro was done, and the visual timer disappeared as expected.

Because I got a notification soon after I re-opened the computer and the timer ended, it doesn't seem like any functionality is particularly broken, it's just a slightly weird behavior for a brief period after the computer wakes.

Also, thanks for your work on this program! I love it.

**Comment by Yoi-Nami-Ra** [comment]
Yes. This is a known problem and should be fixed in next release.
