### ISSUE TITLE
dmg code is not signed

### ISSUE THREAD

**Issue by ssbarnea** [coddingtonbear/taskwarrior-pomodoro#45]
dmg code is not signed with an authorized Apple ID and this is a serious distribution issue, as the default security settings prevent such code from being run, for good reasons.
<img width="532" alt="180820-monosnap" src="https://user-images.githubusercontent.com/102495/44347683-6154e680-a490-11e8-9051-459406a01f62.png">

**Comment by Yoi-Nami-Ra** [comment]
Thanks for quick feedback. I will fix that in a moment.

**Comment by Yoi-Nami-Ra** [comment]
Just a quick question. The gatekeeper complains about the DMG file, or about the app inside it?

**Comment by ssbarnea** [comment]
Apparently is the DMG, not sure about the App inside.

**Comment by dasdom** [comment]
Is this the reason why the DMG is now missing from the release page?

**Comment by Yoi-Nami-Ra** [comment]
DMG is back and ready for testing.

**Comment by ssbarnea** [comment]
I can confirm that the DMG is correctly signed now and I was able to correct open it and install it. Sadly on MacOS Mojave application starts but I get a color wheel of death when I hover over its menu icon. Still, this bug should be closed. Thanks.

See https://github.com/coddingtonbear/taskwarrior-pomodoro/issues/46
