### ISSUE TITLE
Color wheel of death when hovering over application icon in menu

### ISSUE THREAD

**Issue by ssbarnea** [coddingtonbear/taskwarrior-pomodoro#46]
On latest MacOS Mojave (beta 6), application (1.8.0) is starting but is not responding at all causing a color wheel of death when hovering over application icon in menu.

I was able to take a sample before killing it.
[Sample of Taskwarrior Pomodoro.txt](https://github.com/coddingtonbear/taskwarrior-pomodoro/files/2315779/Sample.of.Taskwarrior.Pomodoro.txt)

**Comment by Yoi-Nami-Ra** [comment]
Unfortunately, I won't be able to work on that bug until I get my hands on Mojave.

**Comment by Yoi-Nami-Ra** [comment]
I've looked at this issue once again.

It hangs while waiting for a call to taskwarrior to finish.

Either the app is struggling to make a call on Mojave or taskwarrior is not yet configured and is waiting for input.

Can you test it with the latest release?

**Comment by Yoi-Nami-Ra** [comment]
I couldn't find any problems with  Mojave nor there are any reports others having them so I'm closing this.
