### ISSUE TITLE
validity of taskwarrior-pomodoro-1.8.0.dmg

### ISSUE THREAD

**Issue by core-code** [coddingtonbear/taskwarrior-pomodoro#48]
since the 
taskwarrior-pomodoro-1.8.0.dmg
file was silently replaced after it has first been uploaded and the checksum changed from
307f017d1ad14721637196e27af00fe2428e4afa8c10bc238b70e8277ccd0486
to
07aad9949cf7ec5752d5da87333c52f07654b0c480b18779afaec0f5debb488a

could you please confirm that this is a valid release that has not been tampered with?

the app is validly signed but it is signed by 'Jaroslaw Wojtasik' instead of 'Adam Coddington'. whats up?

**Comment by kmarekspartz** [comment]
#44 and #45 might help clear this up

**Comment by Yoi-Nami-Ra** [comment]
For now, I'm the one maintaining releases, so that's why a change of ID's
And as @kmarekspartz  mentioned (thanks !), because I messed up the process and used wrong certs 
I had to replace the file. Sorry for doing so silently.

**Comment by core-code** [comment]
thanks a lot, sounds good. let's close this.
