### ISSUE TITLE
launch path not accessible

### ISSUE THREAD

**Issue by zerotao** [coddingtonbear/taskwarrior-pomodoro#5]
I am getting the error "launch path not accessible" with both the downloaded and locally built versions.

e.g.  2015-12-20 21:43:19.004 Taskwarrior Pomodoro[1640:23669] launch path not accessible
This is the only message reported in the logs.
When this happens the Icon shows up but clicking the icon has no effect.

**Comment by coddingtonbear** [comment]
It's a little hard to say, but it _sounds_ like it might be that your `task` isn't at the path that Taskwarrior Pomodoro is expecting;   if you run `which task` from the commandline, is the reply not `/usr/local/bin/task`?

**Comment by coddingtonbear** [comment]
I'm closing this since I haven't heard from you in a month; let me know if you're still having trouble!

Cheers!
