### ISSUE TITLE
Hook with timewarrior  ......

### ISSUE THREAD

**Issue by anoopd** [coddingtonbear/taskwarrior-pomodoro#53]
Thank you for such a great piece of software  . Is it possible to hook this with timewarrior so that we can get the total time spend on project  ?

**Comment by atomdmac** [comment]
For what it's worth, the [hook that comes with TimeWarrior](https://timewarrior.net/docs/taskwarrior.html) seems to fill this need pretty well for me.

**Comment by beatgammit** [comment]
The main thing to take into account is that timewarrior might not be in the path, so make sure that's the case. See #29 for one such solution.
