### ISSUE TITLE
Task Not Activated on Pomodoro Start

### ISSUE THREAD

**Issue by atomdmac** [coddingtonbear/taskwarrior-pomodoro#54]
# Environment
- macOS Mojave 10.14.6
- Reproduced with `taskwarrior-pomodoro` 1.8.0 and 1.9.0 Beta 2

# Steps to Reproduce
1. Create a new task via `task add...`
2. Open `taskwarrior-pomodoro`
3. Start a new pomodoro for the new task
4. Back in terminal, do `task list`
5. Notice that no tasks are marked as `active`

It's worth noting that if I manually mark the task as `active` from the terminal, `taskwarrior-pomodoro` _will_ deactivate it (i.e. `task stop`) when the pomodoro is over.

Has anyone else experienced this?

**Comment by willybarro** [comment]
This is happening for me too!

In my case, it happens when the ```on-modify.timewarrior``` script is present in ```~/.task/hooks```; by removing the script, taskwarrior-pomodoro goes back to start/stopping the tasks normally.

**Comment by ctrl-b** [comment]
This is related to this: https://github.com/coddingtonbear/taskwarrior-pomodoro/issues/29#issuecomment-277893565

I did follow the steps explained thereand now it's working

~~If I remove the hook (on-modify.timewarrior) the app can start/stop the tasks but timewarrior is not tracking the time on the task~~

**Comment by beatgammit** [comment]
Issue has been resolved. I don't know what we can do better here. Closing.
