### ISSUE TITLE
Filtering by project

### ISSUE THREAD

**Issue by gfrivolt** [coddingtonbear/taskwarrior-pomodoro#7]
How can I set up a filter to show only specific project(s)?

**Comment by coddingtonbear** [comment]
You can find instructions in [the readme](https://github.com/coddingtonbear/taskwarrior-pomodoro#task-list-filter) for setting your default filter.  The TLDR is that you set the configuration setting `pomodoro.defaultFilter` in your `~/.taskrc` to the filter you'd use at the commandline to limit task results.

Let me know if you have any other questions; cheers!

**Comment by gfrivolt** [comment]
Thanks, I see it works. I need to choose "Refresh Tasks" two times to get the list updated. That was misleading a bit.
